import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:go_router/go_router.dart';
import '../../../../core/di/injection.dart';
import '../../../../core/theme/app_colors.dart';
import '../../../../core/utils/format_utils.dart';
import '../../../cart/domain/entities/cart.dart';
import '../../../cart/presentation/bloc/cart_bloc.dart';
import '../../domain/entities/order.dart';
import '../bloc/order_bloc.dart';
import '../bloc/order_event.dart';
import '../bloc/order_state.dart';

class PaymentMethodScreen extends StatefulWidget {
  final Map<String, dynamic> checkoutData;

  const PaymentMethodScreen({super.key, required this.checkoutData});

  @override
  State<PaymentMethodScreen> createState() => _PaymentMethodScreenState();
}

class _PaymentMethodScreenState extends State<PaymentMethodScreen> {
  PaymentMethod _selectedMethod = PaymentMethod.cash;

  @override
  Widget build(BuildContext context) {
    final Cart cart = widget.checkoutData['cart'];

    return BlocProvider(
      create: (context) => getIt<OrderBloc>(),
      child: BlocListener<OrderBloc, OrderState>(
        listener: (context, state) {
          if (state is OrderSuccess) {
            // Clear cart on success
            context.read<CartBloc>().add(ClearCart());

            // Navigate to success or orders
            context.go('/home'); // In a real app, go to order confirmation
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(
                content: Text('Commande passée avec succès !'),
                backgroundColor: AppColors.success,
              ),
            );
          } else if (state is OrderError) {
            ScaffoldMessenger.of(context).showSnackBar(
              SnackBar(
                content: Text(state.message),
                backgroundColor: AppColors.error,
              ),
            );
          }
        },
        child: Scaffold(
          backgroundColor: AppColors.backgroundDark,
          appBar: AppBar(title: const Text('Paiement')),
          body: Padding(
            padding: const EdgeInsets.all(24),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Text(
                  'Choisissez votre moyen de paiement',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 18,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                const SizedBox(height: 24),

                _buildPaymentOption(
                  'Paiement à la livraison',
                  'Payez en espèces lors de la réception',
                  Icons.payments_outlined,
                  PaymentMethod.cash,
                ),
                const SizedBox(height: 16),
                _buildPaymentOption(
                  'Orange Money',
                  'Rapide et sécurisé',
                  Icons.phone_android,
                  PaymentMethod.orangeMoney,
                ),
                const SizedBox(height: 16),
                _buildPaymentOption(
                  'Moov Money',
                  'Efficace et simple',
                  Icons.phone_android,
                  PaymentMethod.moovMoney,
                ),

                const Spacer(),

                // Final Total
                Container(
                  padding: const EdgeInsets.all(16),
                  decoration: BoxDecoration(
                    color: AppColors.cardDark,
                    borderRadius: BorderRadius.circular(16),
                  ),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      const Text(
                        'Montant à payer',
                        style: TextStyle(color: Colors.white, fontSize: 16),
                      ),
                      Text(
                        FormatUtils.formatPrice(cart.totalAmount),
                        style: const TextStyle(
                          color: AppColors.primary,
                          fontSize: 20,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                    ],
                  ),
                ),
                const SizedBox(height: 24),

                // Confirm Button
                BlocBuilder<OrderBloc, OrderState>(
                  builder: (context, state) {
                    return SizedBox(
                      width: double.infinity,
                      height: 56,
                      child: ElevatedButton(
                        onPressed: state is OrderLoading
                            ? null
                            : () {
                                final order = Order(
                                  id: '', // Will be generated by Firestore
                                  userId:
                                      'temp_user_id', // Should get from Auth
                                  userName: 'Utilisateur',
                                  userPhone: widget.checkoutData['phone'],
                                  items: cart.items
                                      .map(
                                        (item) => OrderItem(
                                          productId: item.productId,
                                          productName: item.productName,
                                          price: item.price,
                                          quantity: item.quantity,
                                          option: item.preparationOption,
                                        ),
                                      )
                                      .toList(),
                                  totalPrice: cart.totalPrice,
                                  deliveryFee: cart.deliveryFee,
                                  totalAmount: cart.totalAmount,
                                  deliveryAddress:
                                      widget.checkoutData['address'],
                                  status: OrderStatus.pending,
                                  paymentMethod: _selectedMethod,
                                  paymentStatus: 'pending',
                                  orderedAt: DateTime.now(),
                                );

                                context.read<OrderBloc>().add(
                                  CreateOrderRequested(order),
                                );
                              },
                        child: state is OrderLoading
                            ? const CircularProgressIndicator(
                                color: AppColors.backgroundDark,
                              )
                            : const Text(
                                'Confirmer la commande',
                                style: TextStyle(
                                  fontSize: 18,
                                  fontWeight: FontWeight.bold,
                                ),
                              ),
                      ),
                    );
                  },
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildPaymentOption(
    String title,
    String subtitle,
    IconData icon,
    PaymentMethod method,
  ) {
    final isSelected = _selectedMethod == method;
    return GestureDetector(
      onTap: () => setState(() => _selectedMethod = method),
      child: Container(
        padding: const EdgeInsets.all(16),
        decoration: BoxDecoration(
          color: AppColors.cardDark,
          borderRadius: BorderRadius.circular(16),
          border: Border.all(
            color: isSelected ? AppColors.primary : Colors.white10,
            width: 2,
          ),
        ),
        child: Row(
          children: [
            CircleAvatar(
              backgroundColor: isSelected
                  ? AppColors.primary.withValues(alpha: 0.1)
                  : Colors.white10,
              child: Icon(
                icon,
                color: isSelected ? AppColors.primary : Colors.white,
              ),
            ),
            const SizedBox(width: 16),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    title,
                    style: const TextStyle(
                      color: Colors.white,
                      fontSize: 16,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  Text(
                    subtitle,
                    style: const TextStyle(
                      color: AppColors.textGrey,
                      fontSize: 12,
                    ),
                  ),
                ],
              ),
            ),
            if (isSelected)
              const Icon(Icons.check_circle, color: AppColors.primary)
            else
              const Icon(Icons.radio_button_off, color: Colors.white10),
          ],
        ),
      ),
    );
  }
}
